### ISSUE TITLE
[help] Conta no slack desativada

### ISSUE THREAD

**Issue by bartier** [training-center/slack#10]
Saudações pessoal,

Bastante tempo atrás eu desativei minha conta no Training Center para organizar meus workspaces no meu e-mail pessoal e agora gostaria de voltar a participar e contribuir na comunidade, no entanto conforme a evidência abaixo necessito de entrar em contato com algum administrador para ativar minha conta novamente (não encontrei opção para ativar sozinho).
![image](https://user-images.githubusercontent.com/18057391/62737083-62668700-ba05-11e9-8ead-1ea2b7e97d53.png)

Por gentileza, alguém saberia dizer quem/como entrar em contato com os responsáveis? Há alguma maneira para ativar?

Obrigado desde já.
Att,
Vitor

**Comment by adeonir** [comment]
Fala @bartier, qual teu email de cadastro no slack?

**Comment by bartier** [comment]
@adeonir Opa, segue: <email_deleted>

**Comment by adeonir** [comment]
@bartier feito! 👍

**Comment by bartier** [comment]
Obrigado @adeonir!

Irei encerrar a issue.
