### ISSUE TITLE
Migração para Rocket.Chat?

### ISSUE THREAD

**Issue by goliveiradev** [training-center/slack#8]
Pessoal, lendo o comentário do @woliveiras [aqui](https://github.com/training-center/mentoria/issues/927#issuecomment-366935320)

> Pelo Slack a gente não consegue por conta do histórico que é apagado quando atinge 10 mil mensagens (tipo todo dia). :cry:

Nunca foi cogitado o https://rocket.chat/ ? Ele pode ser instalado (freezão) em uma VPS barata e não tem limite de mensagens. Eu entrei recentemente no Slack, e imagino que muita conversa boa sumiu e foi perdida para sempre.

Eu entraria na vaquinha para pagar um VPS barato na gringa, plano anual.

**Comment by lasombra** [comment]
Que tal Riot.im, https://about.riot.im/?

**Comment by luizbills** [comment]
@goliveira-dev eu acho uma boa também. Porém tem que ver até onde uma VPS barata iria aguentar e se não acabaria ficando caro para o CT.

@lasombra eu prefiro cogitar o rocket.chat mesmo. Ele foi/é desenvolvido por brasileiros e a comunidade é bem maior.

**Comment by lasombra** [comment]
Mas com protocolo fechado, o que limita o uso aos clientes que eles
oferecem. O Riot.im implementa o protocolo Matrix, o que deixa as pessoas
usarem o cliente que as deixam mais confortáveis.

**Comment by goliveiradev** [comment]
@luizbills realmente, tem que ver se financeiramente vale a pena. Acho que vpn que roda um wordpress da vida, deve rodar bem o Rocket.

@lasombra parece bem interessante esse chat. Eu não acho que DEVE ser o Rocket.Chat, basta uma plataforma que não tenha as limitações do Slack.

Cabe o pessoal dar mais sugestões de serviços e o CoreTeam do TC dar uma opinião.

@lasombra só não entendi como eles hosteam free um chat sem limitações. Não vi como eles conseguem viabilizar o projeto Riot.im

**Comment by lasombra** [comment]
@goliveira-dev Eu não conheço a estrutura deles porém eles guardam histórico sim. Um ponto que eu também não conheço são os limites da plataforma.

**Comment by cenoura** [comment]
eu posso disponibilizar uma VPS para rodar uma instalação do rocket chat se o pessoal quiser testar e ver como fica o desempenho/funcionamento da parada 😄

**Comment by alinebastos** [comment]
Pessoal, eu acho bem interessante a ideia, mas tem que ver se o pessoal migraria. Não adianta nada mudar e o chat novo ficar às moscas. Eu sou uma que relutaria pra migrar, sendo bem sincera.

**Comment by cenoura** [comment]
@alinebastos eu, inicialmente, relutaria também, pois tenho vários grupos no Slack, mas levaria em consideração os benefícios de ter o histórico de mensagens completo disponível, por exemplo. E acho que é tudo uma questão de adaptação. Podemos pensar em uma estratégia de transição, arquivar grupos, criar mensagens automáticas, mudar posts que falam do slack para o rocket chat, até a página do slackin poderia redirecionar para ele. Mas, é claro, no final de tudo vai depender do pessoal comprar a idéia! :)

**Comment by alinebastos** [comment]
Pois é, pq são quase 2500 pessoas lá no slack nesse momento.

**Comment by khaosdoctor** [comment]
Olha galera, sendo sincero, eu não sou muito fã de trocar agora. O histórico é importante, mas não acho que seja um fator decisivo para a gente migrar toda a comunidade (que basicamente acontece no slack) para outro serviço... Mas é minha opinião

**Comment by woliveiras** [comment]
Fala, galera!

> Nunca foi cogitado o https://rocket.chat/ ?

Foooooi. Fizemos um levantamento uma vez e a galera não migraria de app porque usam o Slack da empresa e não gostariam/não poderiam instalar mais um outro comunicador no celular ou mesmo abrir algo diferente no trampo.

--- 

A grande verdade é que o histórico não deve ser importate pra gente, pois tudo o que deve ser discutido e mantido histórico (coisas muito importantes), normalmente, deve ser feito em **vias públicas** como o GitHub pra gente "prestar contas" de qualquer coisa que fazemos para a comunidade. :grimacing:

Nós estamos tentando levar o pessoal para o [forum](https://github.com/training-center/forum) sempre que é algo que deveria ser exposto/guardado para outras pessoas verem. :grin:
